name: Build Auto_Bangumi Docker

on:
  release:
    types:
      - released

jobs:
  job1:
    name: buildx amd64
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set Version
        id: set-version
        run: |
          echo "::set-output name=version::${GITHUB_REF:10}"
          echo "ReleaseTag=${GITHUB_REF:10}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - 
        name: Buildx-amd64
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
          push: true
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}
          tags: |
             ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:${{ steps.set-version.outputs.version }}_amd64

  job2:
    name: buildx arm64
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set Version
        id: set-version
        run: |
          echo "::set-output name=version::${GITHUB_REF:10}"
          echo "ReleaseTag=${GITHUB_REF:10}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - 
        name: Buildx-arm64
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/arm64
          push: true
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}
          tags: |
             ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:${{ steps.set-version.outputs.version }}_arm64

  job3:
    name: buildx arm
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set Version
        id: set-version
        run: |
          echo "::set-output name=version::${GITHUB_REF:10}"
          echo "ReleaseTag=${GITHUB_REF:10}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - 
        name: Buildx-arm
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/arm
          push: true
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}
          tags: |
             ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:${{ steps.set-version.outputs.version }}_arm

  job4:
    needs: [job1, job2, job3]
    name: version tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Version
        id: set-version
        run: |
          echo "::set-output name=version::${GITHUB_REF:10}"
          echo "ReleaseTag=${GITHUB_REF:10}"
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: create version tag
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:${{ steps.set-version.outputs.version }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:${{ steps.set-version.outputs.version }}_amd64 \
            ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:${{ steps.set-version.outputs.version }}_arm64 \
            ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:${{ steps.set-version.outputs.version }}_arm

      - name: create latest-amd64 tag
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:latest_amd64 \
            ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:${{ steps.set-version.outputs.version }}_amd64

      - name: create latest-arm64 tag
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:latest_arm64 \
            ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:${{ steps.set-version.outputs.version }}_arm64

      - name: create latest-arm tag
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:latest_arm \
            ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:${{ steps.set-version.outputs.version }}_arm

      - name: create latest tag
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:latest \
            ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:latest_amd64 \
            ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:latest_arm64 \
            ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi:latest_arm

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_HUB_USERNAME }}/auto_bangumi
          short-description: Auto_Bangumi Image
          readme-filepath: ./README.md